---
- name: Ufw configuration
  hosts: all
  become: true
  tasks:
  - name: Install ufw
    ansible.builtin.package:
      name: ufw
      state: present

  - name: OpenSSH port open and prevent brute force
    community.general.ufw:
      rule: limit
      name: OpenSSH

  - name: Start and enable ufw service
    community.general.ufw:
      state: enabled
      policy: "deny"
      logging: "high"
    notify: Reload ufw

  - name: Kubernetes ports
    community.general.ufw:
      rule: allow
      port: "{{ item }}"
      proto: tcp
    with_items:
      - 6443
      - 2379
      - 2380
      - 10250
      - 10259
      - 10257
    notify: Reload ufw
    when: inventory_hostname in groups['controlplane']

  - name: Kubernetes ports
    community.general.ufw:
      rule: allow
      port: "{{ item }}"
      proto: tcp
    with_items:
      - 10250
      - '30000:32767'
    notify: Reload ufw
    when: inventory_hostname in groups['workers']

  handlers:
    - name: Reload ufw
      community.general.ufw:
        name: ufw
        state: reloaded
